<a href="https://colab.research.google.com/github/Aswanurrehman/Data-Science/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr.ndim)

<class 'numpy.ndarray'>
1


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4,5,6.6])

In [ ]:
arr.dtype

dtype('float64')

##Time

In [ ]:
lst = [1]*10000

In [ ]:
print(lst)
print(len(lst))
print(type(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
arr = np.ones(10000,dtype="uint8")

In [ ]:
print(arr)

[1 1 1 ... 1 1 1]


In [ ]:
%timeit sum(lst)

The slowest run took 4.09 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 67.1 µs per loop


In [ ]:
%timeit arr.sum()

The slowest run took 361.64 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 13.9 µs per loop


In [ ]:
%timeit sum(arr)

100 loops, best of 5: 2.35 ms per loop


2d array

In [ ]:
arr = np.ones((3,4),dtype="uint8")
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#Slicing

In [ ]:
arr= np.arange(5,25,2)
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [ ]:
arr[2:5]

array([ 9, 11, 13])

list ki slicing me 1 new copy banti hai.

jabki numpy me old change ho jati hai new nahi banti.